linters:
  enable-all: true
  disable:
    - deadcode
    - depguard
    - exhaustivestruct
    - exhaustruct
    - goerr113
    - golint
    - ifshort
    - interfacer
    - lll
    - maligned
    - nosnakecase
    - scopelint
    - structcheck
    - varcheck
    - varnamelen
    - wrapcheck
    - wsl


issues:
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - gochecknoglobals
        - testpackage
