linters:
  enable-all: true
  disable:
    - copyloopvar
    - depguard
    - err113
    - exhaustruct
    - intrange
    - lll
    - tenv
    - varnamelen
    - wrapcheck
    - wsl


issues:
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - gochecknoglobals
        - testpackage
